# pom-gen-plugin

This is a sbt plugin which support generating pom.xml.

## How to use

First you clone and publish to local.

    > sbt
    @sbt console
    > publish-local

Then you set plugin setting to your sbt setting.
You make project/plugins.sbt file, and addbelow.

    addSbtPlugin("com.geishatokyo.sbt.plugin" % "pom-gen-plugin" % "0.1")


## Commands

### gen-pom

This task generates pom file.

Difference with make-pom

* it makes `pom.xml` file at each project directory.
* it overwrites existing `pom.xml` only settings which is generated by `make-pom'
* it replaces `<scala.version>` property to appropriate scala version.






